//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_1__Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int ID_Employee { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CCCD { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Address { get; set; }
        public string Position { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Working_time { get; set; }
        public Nullable<int> Extra { get; set; }
        public virtual double Cal_Salary(int a , int b) { return 0; }
    }
}
