//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_1__Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class READER
    {
        public READER()
        {
            this.Borrow_Book = new HashSet<Borrow_Book>();
        }
    
        public int ID_rd { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CCCD { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Address { get; set; }
        public int N_books_br { get; set; }
    
        public virtual ICollection<Borrow_Book> Borrow_Book { get; set; }
    }
}
